if (typeof window !== "undefined") {
  require("bootstrap/dist/js/bootstrap");
}

export default function Head() {
  return (
    <head>
      <title>Create Next App</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
      <link href="https://fonts.googleapis.com/css2?family=Urbanist:wght@300;400;500;600;700;800;900&display=swap" rel="stylesheet" />
      <link rel="stylesheet" href="/assets/css/fontAwesome5Pro.css" />
      <link rel="stylesheet" href="/assets/css/flaticon.css" />
      <link rel="stylesheet" href="/assets/css/default.css" />
    </head>
  )
}
