import './globals.css'
import {SessionProvider} from "next-auth/react";
import Provider from "@/components/Provider";
import Header from "@/components/Layout/Header";


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
      <Provider>
          <Header />
      {children}
      </Provider>
      </body>
    </html>
  )
}
