import './globals.css'
import 'react-responsive-modal/styles.css';
import './index.scss';
import 'react-toastify/dist/ReactToastify.css';
import Provider from "@/components/Provider";
import Header from "@/components/Layout/Header";
import ThemeProvider from "@/components/ThemeProvider";
import Head from "next/head";
if (typeof window !== "undefined") {
  require("bootstrap/dist/js/bootstrap");
}
import "../../public/assets/css/default.css";
import "../../public/assets/css/fontAwesome5Pro.css";
import "../../public/assets/css/flaticon.css";

export const metadata = {
  title: 'SharkServers.pl',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="body-bg">
      <Provider>
          <ThemeProvider defaultTheme="dark">
              <Header />
              {children}
          </ThemeProvider>
      </Provider>
      </body>
    </html>
  )
}
