import './globals.css'
import type {Metadata} from 'next'
import Header from "@/components/layout/Header.component";
import Footer from "@/components/layout/Footer.component";

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <html lang="en" className={"dark"}>
        <body className={"bg-slate-900"}>
        <Header />
        <main className="container mx-auto py-6 sm:px-6 lg:px-8 flex flex-col">
            {children}
        </main>
        <Footer />
        </body>
        </html>
    )
}
